### PR TITLE
Add a setting option "Skip break when running fullscreen apps"

### PR DESCRIPTION
**Pull request by Enna1**
Hi, I add a setting option for skipping eyes' break when running foreground fullscreen apps.

The files changed are formatted by the clang format style file provided in this project.

### CODE REVIEW

**Comment by yalov** [comment]
Hi, thank you for the involvement.

Nothing in the project (.pro) specify, that clang format need to be run, and now there are 600 lines of difference.
Could you remove all formatting changes, so I could grasp new feature in the diff?

**Comment by Enna1** [comment]
> Hi, thank you for the involvement.
> 
> Nothing in the project (.pro) specify, that clang format need to be run, and now there are 600 lines of difference.
> Could you remove all formatting changes, so I could grasp new feature in the diff?
> 
> 
> 
> 

Sorry, I will remove all formatting changes.

**Comment by Enna1** [comment]
> Hi, thank you for the involvement.
> 
> Nothing in the project (.pro) specify, that clang format need to be run, and now there are 600 lines of difference.
> Could you remove all formatting changes, so I could grasp new feature in the diff?

Hi, I removed all formatting changes.
Please see the diff.
Thanks!

**Comment by yalov** [comment]
looks pretty good. 
One question though, 

https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ne-shellapi-query_user_notification_state
> QUNS_BUSY | A full-screen application is running or Presentation Settings are applied.

they are talking not about the maximizing an application window to a full screen, but about _really_ full screen, like F11 in the browsers or any video in a browser or a videoplayer in the fullscreen mode, aren't they?

**Comment by Enna1** [comment]
> looks pretty good. 
> One question though, 
> 
> https://docs.microsoft.com/en-us/windows/win32/api/shellapi/ne-shellapi-query_user_notification_state
> > QUNS_BUSY | A full-screen application is running or Presentation Settings are applied.
> 
> they are talking not about the maximizing an application window to a full screen, but about _really_ full screen, like F11 in the browsers or any video in a browser or a videoplayer in the fullscreen mode, aren't they?
> 
> 

Yes, you are right.
It's not about a maximizing window.
It's about really fullscreen application, like F11 in chrome or videoplayer in the fullscreen(exclusive mode) or powerpoint presentation.

**Comment by yalov** [comment]
thank you again. I will release it in a few days.

**Pull request merged**
